CREATE TABLE IF NOT EXISTS `role`(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) UNIQUE
);

CREATE TABLE IF NOT EXISTS `user`(
    username VARCHAR(255) PRIMARY KEY,
    password VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS `user_role`(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_username VARCHAR(255),
    role_id BIGINT,
    FOREIGN KEY(user_username) REFERENCES `user`(username),
    FOREIGN KEY(role_id) REFERENCES `role`(id)
);

CREATE TABLE IF NOT EXISTS student(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstname VARCHAR(255),
    lastname VARCHAR(255),
    birthdate DATE,
    username VARCHAR(255),
    FOREIGN KEY(username) REFERENCES `user`(username)
);

CREATE TABLE IF NOT EXISTS note(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE,
    subject VARCHAR(30),
    note_value NUMERIC(3, 2),
    student_id BIGINT,
    FOREIGN KEY (student_id) REFERENCES student(id)
);

